version: 0.2

phases:
  install:
    commands:
      - echo "ðŸ“¦ Installing rsync and ssh..."
      - apt-get update
      - apt-get install -y rsync ssh

  build:
    commands:
      - echo "ðŸ— Building Strapi..."
      - npm install
      - npm run build

  post_build:
    commands:
      - echo "ðŸš€ Deploying to EC2: $EC2_HOST"
      
      # Prepare SSH key from environment variable (stored securely in Secrets Manager/SSM)
      - mkdir -p ~/.ssh
      - echo "$EC2_SSH_KEY" > ~/.ssh/ec2-key.pem
      - chmod 600 ~/.ssh/ec2-key.pem

      # Sync files directly to Strapi app folder on EC2
      - rsync -avz -e "ssh -o StrictHostKeyChecking=no -i ~/.ssh/ec2-key.pem" \
          --exclude node_modules \
          --exclude .git \
          --exclude .env \
          ./ ubuntu@$EC2_HOST:/home/ubuntu/strapi-on-aws/my-strapi-app/my-app/

      # Install dependencies, build, and restart Strapi on EC2
      - ssh -o StrictHostKeyChecking=no -i ~/.ssh/ec2-key.pem ubuntu@$EC2_HOST << 'EOF'
          cd /home/ubuntu/strapi-on-aws/my-strapi-app/my-app
          npm install --production
          npm run build
          pm2 restart strapi || pm2 start "npm run start" --name strapi
          echo "âœ… Deployment complete!"
        EOF
