version: '3.8'

services:
  strapi:
    build: .
    container_name: strapi-app
    restart: unless-stopped
    env_file: .env
    ports:
      - '1337:1337'
    depends_on:
      - postgres
    volumes:
      - ./app:/app
      - /app/node_modules

  postgres:
    image: postgres:15
    container_name: strapi-postgres
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
      POSTGRES_DB: strapi
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
