# docker-compose.yml
version: '3.8'

services:
  strapi:
    build: .
    container_name: strapi-app
    env_file: .env
    ports:
      - '1337:1337'
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:15
    container_name: strapi-postgres
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USERNAME} -d ${DATABASE_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  postgres_data:
