# Use Node.js base image
FROM node:18

# Set working directory
WORKDIR /app

# Copy package files
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install

# Copy the rest of the app
COPY . .

# Build the admin panel
RUN NODE_OPTIONS="--max-old-space-size=4096" npm run build


# Expose the port Strapi runs on
EXPOSE 1337

# Start the Strapi application
CMD ["npm", "start"]
