version: 0.2

phases:
  install:
    commands:
      - echo "Installing rsync and SSH"
      - yum update -y
      - yum install -y rsync openssh-clients

  build:
    commands:
      - echo "Building Strapi..."
      - npm install
      # Uncomment ONLY if you customized admin UI:
      # - npm run build

  post_build:
    commands:
      - echo "Deploying to EC2..."
      - echo "EC2_HOST: $EC2_HOST"
      - mkdir -p ~/.ssh
      - echo "$EC2_SSH_KEY" > ~/.ssh/ec2-key.pem
      - chmod 600 ~/.ssh/ec2-key.pem
      - rsync -avz -e "ssh -o StrictHostKeyChecking=no -i ~/.ssh/ec2-key.pem" --exclude node_modules --exclude .git --exclude .env ./ ubuntu@$EC2_HOST:~/strapi-deploy/
      - echo "$EC2_ENV" > .env.tmp
      - rsync -e "ssh -o StrictHostKeyChecking=no -i ~/.ssh/ec2-key.pem" .env.tmp ubuntu@$EC2_HOST:~/strapi-deploy/.env
      - ssh -o StrictHostKeyChecking=no -i ~/.ssh/ec2-key.pem ubuntu@$EC2_HOST "set -e; cd ~/strapi-deploy; cp -rf * /home/ubuntu/strapi-on-aws/my-strapi-app/my-app/; cd /home/ubuntu/strapi-on-aws/my-strapi-app/my-app; npm install --production; pm2 stop strapi-app || true; pm2 start npm --name 'strapi-app' -- start; pm2 save; echo '✅ Deployment complete!'"
