version: 0.2

phases:
  install:
    commands:
      # This command will list all files and folders recursively from the starting point.
      # The 'cd' command has been removed to ensure this command runs.
      - "ls -R"

