version: 0.2

env:
  image: aws/codebuild/standard:7.0
  runtime-versions:
    nodejs: 18

phases:
  install:
    commands:
      # ADD THIS UNIQUE LINE
      - "echo '✅ Successfully loaded buildspec.yml from repository!'"
      
      # This command navigates to the root of your Strapi application
      - "cd my-strapi-app/my-app"
      
      # This command installs all your project dependencies
      - "npm install"

  build:
    commands:
      - "cd my-strapi-app/my-app"
      - "npm run build"

artifacts:
  base-directory: my-strapi-app/my-app
  files:
    - '**/*'

cache:
  paths:
    - my-strapi-app/my-app/node_modules/**/*

