version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - "echo '🔧 Using Node $(node --version)'"
      - "echo '🔧 Compiler: $(g++ --version)'"
      - "cd my-strapi-app/my-app"
      - "npm install"

  build:
    commands:
      - "npm run build"

artifacts:
  base-directory: my-strapi-app/my-app
  files:
    - '**/*'

cache:
  paths:
    - my-strapi-app/my-app/node_modules/**/*
