version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "🔍 Finding package.json..."
      - find . -name "package.json"
      - cd strapi-on-aws/my-strapi-app/my-app
      - npm install

  build:
    commands:
      - npm run build

artifacts:
  base-directory: strapi-on-aws/my-strapi-app/my-app
  files:
    - '**/*'

cache:
  paths:
    - 'strapi-on-aws/my-strapi-app/my-app/node_modules/**/*'
