version: 0.2

env:
  image: aws/codebuild/standard:7.0
  runtime-versions:
    nodejs: 18

phases:
  install:
    commands:
      - "echo '🔧 Using Node $(node --version)'"
      - "cd my-strapi-app/my-app"
      - "npm ci"

  build:
    commands:
      - "cd my-strapi-app/my-app"
      - "npm run build"

artifacts:
  base-directory: my-strapi-app/my-app
  files:
    - '**/*'

cache:
  paths:
    - my-strapi-app/my-app/node_modules/**/*



