version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "🔍 Current directory: $(pwd)"
      - find . -name "package.json"
      # ✅ Change to the correct directory
      - cd my-strapi-app/my-app
      - echo "✅ Changed to directory: $(pwd)"
      - npm install

  build:
    commands:
      - npm run build

artifacts:
  # ✅ Make sure to package the built app
  base-directory: my-strapi-app/my-app
  files:
    - '**/*'

cache:
  paths:
    - my-strapi-app/my-app/node_modules/**/*
