version: 0.2

env:
  # This is the correct way to specify the image.
  # The buildspec.yml takes precedence over the console UI.
  image: aws/codebuild/standard:7.0
  runtime-versions:
    nodejs: 18

phases:
  install:
    commands:
      # These commands are great for verifying the environment
      - "echo '🔧 Using Node $(node --version)'"
      - "echo '🔧 Compiler: $(g++ --version)'"
      - "cd my-strapi-app/my-app"
      - "npm install"

  build:
    commands:
      - "npm run build"

artifacts:
  base-directory: my-strapi-app/my-app
  files:
    - '**/*'

cache:
  paths:
    - my-strapi-app/my-app/node_modules/**/*

